[project]
name = "mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mcp-cli>=0.6",
    "mcp[cli]",
]

[tool.uv.sources]
mcp = { workspace = true }
